outfile:main.o add_begin.o add_end.o add_middle.o print.o rev_print.o rev_data.o rev_link.o count.o delete.o delete_all.o save.o 
	cc main.c add_begin.c add_end.c add_middle.c print.c rev_print.c rev_data.c rev_link.c count.c delete.c delete_all.c save.c -o outfile
main.o:main.c
	cc -c main.c
add_begin.o:add_begin.c
	cc -c add_begin.c
add_end.o:add_end.c
	cc -c add_end.c
add_middle.o:add_middle.c
	cc -c add_middle.c
print.o:print.c
	cc -c print.c
rev_print.o:rev_print.c
	cc -c rev_print.c
rev_data.o:rev_data.c
	cc -c rev_data.c
rev_link.o:rev_link.c
	cc -c rev_link.c	
count.o:count.c
	cc -c count.c
delete.o:delete.c
	cc -c delete.c
delete_all.o:delete_all.c
	cc -c delete_all.c
save.o:save.c
	cc -c save.c
